version: '3'
services:
  db: 
    image: mariadb:10.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${C5_DB_NAME}
      - MYSQL_USER=${C5_DB_USER}
      - MYSQL_PASSWORD=${C5_DB_PASSWORD}
    restart: on-failure:5
    networks:
      - default
    volumes:
      - ./backup/sql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - 3306
  app:
    image: c5:8.5.2
    volumes:
      - generated:/app/application/config/generated_overrides
      - ./application/themes:/app/application/themes
    restart: on-failure:5
    env_file:
      - .env
    depends_on: 
      - db
    ports:
      - 32733:80
    networks:
      - default
volumes:
  generated: {}
  db: {}